# hostname (and path) to the root eg. http://spf13.com/
baseurl = "https://notsaved.org/"

# Site title
title = "Things I Learnt Today"

# Copyright
copyright = "(c) 2018 Thomas Seropian."

# Language
languageCode = "en-EN"

# "yaml", "toml", "json"
metaDataFormat = "yaml"

# theme to use (located in /themes/THEMENAME/)
theme = "hyde-y"

# pagination
paginate = 10
paginatePath = "page"

# Enable Disqus integration
# disqusShortname = ""

[permalinks]
    post = "/:slug/"

[taxonomies]
    tag = "tags"
    topic = "topics"

[author]
    name = "Thomas Seropian"
    email = "thomas@seropian.io"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # You can use markdown here.
    brand = "notsaved.org"
    tagline = "Things I learnt today"
    footline = "code with <i class='fa fa-heart'></i>"

    # Sidebar position
    # false, true, "left", "right"
    sidebar = "left"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Home".
    home = "Home"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "default"

    # Google Analytics.
    googleAnalytics = "UA-74217788-1"
    gravatarHash = "e4970a9b0788eb73c7986635b454812f"


    # Sidebar social links.
    github 	= "tseropian/notsaved" # Your Github profile ID
    linkedin 	= "tseropian/" # Your LinkedIn profile ID (from public URL)
    facebook 	= "tseropian" # Your Facebook profile ID
    twitter 	= "thoomyorke" # Your Twitter profile ID

    truncate = false
[blackfriday]
    angledQuotes = true
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []
